env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:storybook/recommended
  - react-app
  - react-app/jest
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  allowImportExportEverywhere: true
plugins:
  - react
  - '@typescript-eslint'
rules:
  react/react-in-jsx-scope: 0
settings:
  react:
    version: 18.2.0
